"""USFM 3.0 book order and section tags used by the divergence engine.

The table matches the prototype catalog, including books the tool's own book
order does not list. Layout and folding depend on this order staying put.
"""

from __future__ import annotations

# (code, English name, section). Peripherals are omitted.
CATALOG: tuple[tuple[str, str, str], ...] = (
    ("GEN", "Genesis", "OT"),
    ("EXO", "Exodus", "OT"),
    ("LEV", "Leviticus", "OT"),
    ("NUM", "Numbers", "OT"),
    ("DEU", "Deuteronomy", "OT"),
    ("JOS", "Joshua", "OT"),
    ("JDG", "Judges", "OT"),
    ("RUT", "Ruth", "OT"),
    ("1SA", "1 Samuel", "OT"),
    ("2SA", "2 Samuel", "OT"),
    ("1KI", "1 Kings", "OT"),
    ("2KI", "2 Kings", "OT"),
    ("1CH", "1 Chronicles", "OT"),
    ("2CH", "2 Chronicles", "OT"),
    ("EZR", "Ezra", "OT"),
    ("NEH", "Nehemiah", "OT"),
    ("EST", "Esther (Hebrew)", "OT"),
    ("JOB", "Job", "OT"),
    ("PSA", "Psalms", "OT"),
    ("PRO", "Proverbs", "OT"),
    ("ECC", "Ecclesiastes", "OT"),
    ("SNG", "Song of Songs", "OT"),
    ("ISA", "Isaiah", "OT"),
    ("JER", "Jeremiah", "OT"),
    ("LAM", "Lamentations", "OT"),
    ("EZK", "Ezekiel", "OT"),
    ("DAN", "Daniel (Hebrew)", "OT"),
    ("HOS", "Hosea", "OT"),
    ("JOL", "Joel", "OT"),
    ("AMO", "Amos", "OT"),
    ("OBA", "Obadiah", "OT"),
    ("JON", "Jonah", "OT"),
    ("MIC", "Micah", "OT"),
    ("NAM", "Nahum", "OT"),
    ("HAB", "Habakkuk", "OT"),
    ("ZEP", "Zephaniah", "OT"),
    ("HAG", "Haggai", "OT"),
    ("ZEC", "Zechariah", "OT"),
    ("MAL", "Malachi", "OT"),
    ("MAT", "Matthew", "NT"),
    ("MRK", "Mark", "NT"),
    ("LUK", "Luke", "NT"),
    ("JHN", "John", "NT"),
    ("ACT", "Acts", "NT"),
    ("ROM", "Romans", "NT"),
    ("1CO", "1 Corinthians", "NT"),
    ("2CO", "2 Corinthians", "NT"),
    ("GAL", "Galatians", "NT"),
    ("EPH", "Ephesians", "NT"),
    ("PHP", "Philippians", "NT"),
    ("COL", "Colossians", "NT"),
    ("1TH", "1 Thessalonians", "NT"),
    ("2TH", "2 Thessalonians", "NT"),
    ("1TI", "1 Timothy", "NT"),
    ("2TI", "2 Timothy", "NT"),
    ("TIT", "Titus", "NT"),
    ("PHM", "Philemon", "NT"),
    ("HEB", "Hebrews", "NT"),
    ("JAS", "James", "NT"),
    ("1PE", "1 Peter", "NT"),
    ("2PE", "2 Peter", "NT"),
    ("1JN", "1 John", "NT"),
    ("2JN", "2 John", "NT"),
    ("3JN", "3 John", "NT"),
    ("JUD", "Jude", "NT"),
    ("REV", "Revelation", "NT"),
    ("TOB", "Tobit", "DC"),
    ("JDT", "Judith", "DC"),
    ("ESG", "Esther Greek", "DC"),
    ("WIS", "Wisdom of Solomon", "DC"),
    ("SIR", "Sirach", "DC"),
    ("BAR", "Baruch", "DC"),
    ("LJE", "Letter of Jeremiah", "DC"),
    ("S3Y", "Song of the 3 Young Men", "DC"),
    ("SUS", "Susanna", "DC"),
    ("BEL", "Bel and the Dragon", "DC"),
    ("1MA", "1 Maccabees", "DC"),
    ("2MA", "2 Maccabees", "DC"),
    ("3MA", "3 Maccabees", "DC"),
    ("4MA", "4 Maccabees", "DC"),
    ("1ES", "1 Esdras (Greek)", "DC"),
    ("2ES", "2 Esdras (Latin)", "DC"),
    ("MAN", "Prayer of Manasseh", "DC"),
    ("PS2", "Psalm 151", "DC"),
    ("ODA", "Odae/Odes", "DC"),
    ("PSS", "Psalms of Solomon", "DC"),
    ("EZA", "Ezra Apocalypse", "EX"),
    ("5EZ", "5 Ezra", "EX"),
    ("6EZ", "6 Ezra", "EX"),
    ("DAG", "Daniel Greek", "EX"),
    ("PS3", "Psalms 152-155", "EX"),
    ("2BA", "2 Baruch (Apocalypse)", "EX"),
    ("LBA", "Letter of Baruch", "EX"),
    ("JUB", "Jubilees", "EX"),
    ("ENO", "Enoch", "EX"),
    ("1MQ", "1 Meqabyan/Mekabis", "EX"),
    ("2MQ", "2 Meqabyan/Mekabis", "EX"),
    ("3MQ", "3 Meqabyan/Mekabis", "EX"),
    ("REP", "Reproof", "EX"),
    ("4BA", "4 Baruch", "EX"),
    ("LAO", "Letter to the Laodiceans", "EX"),
)

# Catalog index by book code. Unknown codes sort after the catalog.
ORDER: dict[str, int] = {code: index for index, (code, _, _) in enumerate(CATALOG)}
# English name by book code.
NAME: dict[str, str] = {code: name for code, name, _ in CATALOG}
# Section tag by book code: OT, NT, DC, or EX.
SECTION: dict[str, str] = {code: section for code, _, section in CATALOG}


def book_order(code: str) -> int:
    """Sort key for a book code. Unknown codes sort after the catalog, stably."""
    return ORDER.get(code, 1000 + sum(ord(ch) for ch in code))
